name: Update comments data

on:
  schedule:
    - cron: '0 */6 * * *'   # 每 6 小时跑一次
  workflow_dispatch:        # 也可以手动触发

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps
        run: npm ci

      - name: Run update script
        run: npm run update   # 假设 package.json 里有这个脚本

      - name: Commit & push if changed
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          git diff --quiet && git diff --staged --quiet || git commit -m "chore: auto-update comments data"
          git push
